# Generated by Django 4.1 on 2022-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'incomplete'), (1, 'complete')], default=2),
        ),
    ]
